---
- name: Upgrade all packages to the latest version
	apt:
		name: "*"
		state: latest

- name: install ca-certificates package
	apt:
		name: ca-certificates
		update_cache: yes
		state: present

- name: install apt-transport-https package
	apt:
		name: apt-transport-https
		update_cache: yes
		state: present

- name: install curl
	apt:
		name: curl
		update_cache: yes
		state: present

- name: install gnupg2
	apt:
		name: gnupg2
		update_cache: yes
		state: present

- name: install software-properties-common
	apt:
		name: software-properties-common
		update_cache: yes
		state: present

- name: Install collectl
	apt: name=collectl update_cache=yes state=latest cache_valid_time=3600
  register: installcollectl

- name: Increase filedescriptor limits
	lineinfile: dest=/etc/security/limits.conf line={{ item }} state=present
	with_items:
		- "* soft nofile 1048576"
		- "* hard nofile 1048576"
		- "root soft nofile 1048576"
		- "root hard nofile 1048576"
		- "* soft memlock unlimited"
		- "* hard memlock unlimited"

- name: Increase inotify and memory limits
	sysctl: name={{ item[0] }} value={{ item[1] }} state=present sysctl_file=/etc/sysctl.d/70-limits.conf reload=yes
	with_together:
		- [ 'fs.inotify.max_queued_events', 'fs.inotify.max_user_instances', 'fs.inotify.max_user_watches', 'vm.max_map_count', 'net.ipv4.tcp_max_syn_backlog', 'net.ipv4.tcp_syncookies', 'net.core.wmem_max', 'net.core.rmem_max', 'net.ipv4.tcp_rmem', 'net.ipv4.tcp_wmem', 'net.ipv4.tcp_window_scaling', 'net.core.netdev_max_backlog']
		- [ 1048576, 1048576, 1048576, 262144, 8096, 0, 12582912, 12582912, '10240 87380 12582912', '10240 87380 12582912', 1, 5000]

- name: add docker ubuntu repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
    state: present

- name: add Docker's official GPG key
	command: bash -c "curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -"

- name: install docker
  apt:
    name: docker-ce
    update_cache: yes
    state: present

- name: install docker-compose
  apt:
    name: docker-compose
    update_cache: yes
    state: present

- name: create nf_conntrack file
  shell: 'sysctl -w net.netfilter.nf_conntrack_max=200000'

- name: tunning nf_conntrack
	sysctl:
		name: net.netfilter.nf_conntrack_count
		value: 200000
		state: present

- name: tunning nf_conntrack hashsize
	shell: 'echo 50000 > /sys/module/nf_conntrack/parameters/hashsize'

- name: apply tunning
  shell: 'sysctl -p'
