version: '3'
services:
    simulator:
        image: kanashiro/interscsimulator:test
        environment:
            - RABBITMQ_HOST="192.168.33.254"
        network_mode: "host"
        tty: true
        volumes:
            - ./interscsimulator_output:/interscsimulator/mock-simulators/smart_city_model/output
